version: '2.2'

services:
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    restart: on-failure

volumes:
  db-data:
